using CommonHelpers.Common;
using CommonHelpers.Models;

namespace FlyoutExample.Models;

public class Pilot : BindableBase
{
    private string name;
    private string position;
    private DateTime startDate;
    private double salary;
    private int vacationTotal;
    private int vacationUsed;
    // api props
    private string photoUrl;
    private string gender;
    private string ethnicity;
    private string eyeColor;
    private string hairColor;
    private string hairLength;

    public Pilot()
    {
        Id = Guid.NewGuid().ToString();
    }

    public string Id { get; init; }

    public string Name
    {
        get => name;
        set => SetProperty(ref name, value);
    }

    public string Position
    {
        get => position;
        set => SetProperty(ref position, value);
    }

    public DateTime StartDate
    {
        get => startDate;
        set => SetProperty(ref startDate, value);
    }

    public double Salary
    {
        get => salary;
        set => SetProperty(ref salary, value);
    }

    public int VacationTotal
    {
        get => vacationTotal;
        set => SetProperty(ref vacationTotal, value);
    }

    public int VacationUsed
    {
        get => vacationUsed;
        set => SetProperty(ref vacationUsed, value);
    }

    // properties generated by API

    public string PhotoUrl
    {
        get => photoUrl;
        set => SetProperty(ref photoUrl, value);
    }

    public string Gender
    {
        get => gender;
        set => SetProperty(ref gender, value);
    }

    public string Ethnicity
    {
        get => ethnicity;
        set => SetProperty(ref ethnicity, value);
    }

    public string EyeColor
    {
        get => eyeColor;
        set => SetProperty(ref eyeColor, value);
    }

    public string HairColor
    {
        get => hairColor;
        set => SetProperty(ref hairColor, value);
    }

    public string HairLength
    {
        get => hairLength;
        set => SetProperty(ref hairLength, value);
    }

    public void GeneratePilotFromEmployee(Employee emp, int seed)
    {
        this.Name = emp.Name;
        this.Position = seed % 2 == 0 ? "Captain" : "First Officer";
        this.StartDate = emp.StartDate;
        this.Salary = emp.Salary;
        this.VacationTotal = emp.VacationTotal;
        this.VacationUsed = emp.VacationUsed;
    }
}
